# Generated by Django 4.2.11 on 2026-03-28 18:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.CharField(max_length=100, unique=True)),
                ('grade', models.IntegerField()),
                ('chapter_name', models.CharField(max_length=200)),
                ('chapter_url', models.CharField(max_length=500)),
                ('chapter_difficulty', models.FloatField()),
                ('expected_completion_time_seconds', models.IntegerField()),
                ('subtopics', models.JSONField(default=list)),
                ('prerequisites', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chapter_metadata',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('xp_total', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('badges', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=200, unique=True)),
                ('chapter_id', models.CharField(default='grade8_factorisation', max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('exited_midway', 'Exited Midway')], default='exited_midway', max_length=20)),
                ('correct_answers', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('questions_attempted', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=45)),
                ('retry_count', models.IntegerField(default=0)),
                ('hints_used', models.IntegerField(default=0)),
                ('total_hints_embedded', models.IntegerField(default=135)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('topic_completion_ratio', models.FloatField(default=0.0)),
                ('current_kc', models.CharField(default='KC-01', max_length=20)),
                ('merge_submitted', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.student')),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=50)),
                ('kc_id', models.CharField(max_length=20)),
                ('attempt_number', models.IntegerField(default=1)),
                ('student_answer', models.TextField()),
                ('is_correct', models.BooleanField()),
                ('hints_used', models.IntegerField(default=0)),
                ('hint_level_reached', models.IntegerField(default=0)),
                ('response_time_s', models.FloatField(default=0)),
                ('confidence', models.CharField(default='medium', max_length=10)),
                ('retry_count', models.IntegerField(default=0)),
                ('misconception_bug_id', models.CharField(blank=True, max_length=20, null=True)),
                ('mastery_before', models.FloatField(default=0)),
                ('mastery_after', models.FloatField(default=0)),
                ('bkt_w_behaviour', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.session')),
            ],
            options={
                'db_table': 'question_attempts',
            },
        ),
        migrations.CreateModel(
            name='KCMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kc_id', models.CharField(max_length=20)),
                ('mastery', models.FloatField(default=0.3)),
                ('attempts', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('wrong_count', models.IntegerField(default=0)),
                ('hints_used_total', models.IntegerField(default=0)),
                ('retries_total', models.IntegerField(default=0)),
                ('consecutive_wrong', models.IntegerField(default=0)),
                ('last_confidence', models.CharField(default='medium', max_length=10)),
                ('misconception_counts', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kc_states', to='core.student')),
            ],
            options={
                'db_table': 'kc_mastery',
                'unique_together': {('student', 'kc_id')},
            },
        ),
    ]
